### PR TITLE
Add script to compare output results

### PR DESCRIPTION
**Pull request by mmcfarland**
Using the results given for the unit test, generate a csv file (and console output)
which allows for easy visual comparison to the existing model output.

Connects #38 

Usage:
`python compare_output.py` or `python compare_output.py somefile.json`

Current results:
[compare.csv.txt](https://github.com/WikiWatershed/gwlf-e/files/236925/compare.csv.txt)

### CODE REVIEW

**Comment by caseypt** [comment]
Consider adding a way to distinguish which rows are for the port vs the original. 

Something like this:

| Month        | AvPrecip           | AvEvapo  |
| ------------- |:-------------:| -----:|
| Jan (port)      | 6.89 | .39 |
| Jan (orig.)      | 6.89      |  .30 |

or 

| Month        | AvPrecip (orig.)           | AvPrecip (port)  |
| ------------- |:-------------:| -----:|
| Jan     | 6.89 | 6.89 |
| Feb     | 6.06 | 6.06 |

**Comment by mmcfarland** [comment]
I thought the whitespace under the original month gave it a nice visual grouping when viewed in a spreadsheet.  I'll try filing in that column.

**Comment by mmcfarland** [comment]
Added `month (ours)` to the "actual" row since digging into the orig row was messier.  Updated attachment.

**Comment by caseypt** [comment]
Consider updating the README with usage instructions.

**Comment by caseypt** [comment]
+1. Tested. Looks good.

**Pull request merged**
