### PR TITLE
Sync `master` and `develop`

### PR DESCRIPTION
**Pull request by kellyi**
Some changes in `develop` never made it back into `master`, so this PR should -- I think -- put them back in sync.

### CODE REVIEW

**Comment by kellyi** [comment]
Going to see if I replay the git history manually to re-create what should be on master.

**Comment by kdeloach** [comment]
You could cherry-pick the top 2 commits from here if you'd like: https://github.com/WikiWatershed/gwlf-e/commits/0.5.0

**Comment by kdeloach** [comment]
In the past, I would merge develop into master locally to allow fast forwarding. It avoids the extra merge commit and makes the branch history a little cleaner.

**Comment by kellyi** [comment]
Tried replaying the commits manually and unfortunately there's a merge conflict with the `0.5.0` releases and fixing it seems to break the history, so the unbroken line of commits ends up looking exactly like this one.

**Comment by hectcastro** [comment]
Does this mean that the missing changes aren't in the release?

**Comment by kellyi** [comment]
`release/0.6.0` looks to have all of the code changes that were in develop from 0.5.0, but the commit history does *not* include `0.5.0` and `merge branch 'release/0.5.0'...` commits.

Master doesn't have anything beyond `merge branch 'release/0.4.0'` right now.

**Comment by kdeloach** [comment]
Looking at this now.

**Comment by kdeloach** [comment]
I created a new branch which contains all changes since release 0.4.0 including the missing 0.5.0 release commit.

https://github.com/WikiWatershed/gwlf-e/tree/develop-fixed

I propose that this branch becomes the new `develop` branch and we hard reset `master` to match.

**Comment by kellyi** [comment]
Sounds good to me.

**Comment by kdeloach** [comment]
This can be closed since I updated the develop branch directly. Also, I merged release/0.5.0 and release/0.6.0 branch into master directly, instead of doing a hard reset.

**Comment by kdeloach** [comment]
I've also pushed a minor release just so that the latest release contains the repaired commit history (no code changes).

**Pull request closed without merging**
