### PR TITLE
Add code coverage tool

### PR DESCRIPTION
**Pull request by kdeloach**
To generate code coverage data:

```
coverage run --source gwlf-e/ run.py sample_input.gms
```

To view results:

```
coverage html
cd htmlcov
python -m SimpleHTTPServer
```

### CODE REVIEW

**Comment by caseypt** [comment]
When I run:

```
$ coverage run --source /gwlfe run.py input_4.gms
```

I get the following output (after it runs the model):

```
Coverage.py warning: Module /gwlfe was never imported.
Coverage.py warning: No data was collected.
```

Then, running the `html` command, I get this:

```
$ coverage html
No data to report.
```

**Comment by kdeloach** [comment]
Sorry, typo in my description. Should be `--source gwlfe/` not `--source /gwlfe`.

**Comment by caseypt** [comment]
Ah. Should have caught that. 

Very cool. +1. Still at 88% on the latest `develop`.

**Comment by kdeloach** [comment]
It should be noted that we should never expect this to reach 100% since different data configurations will exercise different parts of the model, by design. One cool feature that I find useful, is that you can click on each file in the HTML report to see which lines were executed or not.

**Comment by mmcfarland** [comment]
To complicate it further, Barry & Ken indicate that it's likely that there are routines/paths that are just old and will never get hit.  Not sure how much confidence we can gather from a particular coverage ratio.

**Pull request merged**
