### PR TITLE
Upgrade to Python 3.9

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Upgrades codebase to Python 3.9, drops support for Python 2.7. See commit messages for details.

Connects #86 
Connects https://github.com/WikiWatershed/model-my-watershed/issues/3165

## Testing Instructions

* Ensure you have Python 3.9 and [pipenv](https://pipenv.pypa.io/en/latest/) installed
* Checkout this branch
* Run `pipenv sync`
* Run `pipenv run nosetests`
  - [x] Ensure all tests pass

### CODE REVIEW

**Comment by rajadain** [comment]
Perhaps we should support Python 3.5 and up for this library, as 3.9 may be too stringent a requirement.

**Review by jwalgran — APPROVED** [review]
Test pass for me locally. Changes look reasonable. Thanks for dividing each type of change into a separate commit for easy review. Follow up with the larger development team to determine if the test value changes are within an acceptable range of variace is a good idea.

**Comment by rajadain** [comment]
I've compiled [this spreadsheet](https://docs.google.com/spreadsheets/d/1-FJkY5SDebF-Bjxrmz7yC9dgy8BQ04bRZYDMqZWnvn0/edit?usp=sharing) to show the differences, sending it to the Stroud team now.

**Comment by rajadain** [comment]
From Anthony:

> My perspective is that these differences are both tolerable and expected, as Python 3 is carrying a different number of significant figures. As you point out, the newer calculations are more accurate.
> 
> For our recent Pollution Assessment Stage 1 work (you’ll be involved in Stage 2), I’ve also noticed rounding differences, and these kinds rounding “errors” can get large when propagated through calculations involving subtractions. Regardless, I think they are all fine and explainable.
> 
> Thanks again for making the update to Python 3!

I'm going to try and relax the Python requirements and test with lower versions of Python as well.

**Comment by rajadain** [comment]
Based on this site: https://w3techs.com/technologies/details/pl-python/3, only 3.3% of users are on Python 3.4, so with Python 3.5 support we'd be able to serve ~96.7% of users. Notably, that website tracks web backend use, which may not accurately represent data science use.

**Comment by rajadain** [comment]
I just tested with a number of different Python versions, and the dependencies we have work with Python 3.7+. Looking at EOL date, 3.7 is valid for another year at least, with 3.6 expiring at the end of this year. So I'm going to adjust the markers to say that we support 3.7, 3.8, and 3.9.

**Comment by rajadain** [comment]
Thanks for the tests. Squashed the fixups. Will make a new release manually once merged, since Travis CI is no more.

**Pull request merged**
