### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by kdeloach**
I reviewed the source code thoroughly, fixed a bunch of errors, and made it run faster

Test by executing the model against some sample GMS files. The numbers should more closely resemble the numbers from the original MapShed results. I did not focus on correctness for this task, so the numbers probably won't match.

Connects #17
Connects #34

### CODE REVIEW

**Comment by kdeloach** [comment]
Updated description.

**Comment by caseypt** [comment]
+1. I did quick review, so you may want to reassign to someone else, but these fixes all look good. The code runs a lot faster (like in a few seconds) and the output looks a lot better.

The CalcCN code path gets hit a lot. I wonder if there is a way to optimize that.

**Comment by lewfish** [comment]
I'm going to make release soon. Do you want to merge this in before then, or do you want to keep iterating on this?

**Comment by kdeloach** [comment]
Merged.

**Pull request merged**
